### ISSUE TITLE
Can't build with openssl 1.0.1k on Alpine 3.5

### ISSUE THREAD

**Issue by racktear** [tarantool/mysql#15]
```
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c: In function 'ma_tls_start':
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c:291:8: warning: implicit declaration of function 'OPENSSL_init_ssl' [-Wimplicit-function-declaration]
   if (!OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL))
        ^~~~~~~~~~~~~~~~
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c:291:25: error: 'OPENSSL_INIT_LOAD_CONFIG' undeclared (first use in this function)
   if (!OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL))
                         ^~~~~~~~~~~~~~~~~~~~~~~~
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c:291:25: note: each undeclared identifier is reported only once for each function it appears in
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c: In function 'ma_tls_verify_server_cert':
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c:675:20: warning: implicit declaration of function 'ASN1_STRING_get0_data' [-Wimplicit-function-declaration]
   cn_str = (char *)ASN1_STRING_get0_data(cn_asn1);
                    ^~~~~~~~~~~~~~~~~~~~~
/rocks/mysql/mariadb-connector-c/libmariadb/secure/openssl.c:675:12: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   cn_str = (char *)ASN1_STRING_get0_data(cn_asn1);
            ^
make[2]: *** [mariadb-connector-c/libmariadb/CMakeFiles/mariadb_obj.dir/build.make:735: mariadb-connector-c/libmariadb/CMakeFiles/mariadb_obj.dir/secure/openssl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:237: mariadb-connector-c/libmariadb/CMakeFiles/mariadb_obj.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

Error: Build error: Failed building.
```

**Comment by rtsisyk** [comment]
Fixed by 20fc0a9b92f77f4aa6ddb245f85a5eb3d20fe274
